### ISSUE TITLE
Game not working

### ISSUE THREAD

**Issue by Luckey-Elijah** [Caleb-Shepard/BOOFALONG#1]
Hi,

I installed your repository to my Windows 7 machine. But when I executed it, the game did not launch. 

These are the logs from the log file:

```
Valheim did not launch.
```

**Comment by tigressine** [comment]
It worked for me on Windows XP.... Have you tried downgrading?

**Comment by Luckey-Elijah** [comment]
Okay. I will try that later.

**Comment by Luckey-Elijah** [comment]
Hi @tgsachse, I downgrade to Windows 7 and it works perfectly! 🗿🙏

**Comment by Caleb-Shepard** [comment]
To elaborate on why this was closed, it was a duplicate of https://github.com/pypa/twine/issues/153#issuecomment-168131494
